displayName=Better Clan Broadcasts
author=Snape Grass
description=A plugin that prepends clan broadcasts with the members clan rank icon
tags=clan,broadcast,rank,icon,chat,clanchat
version= 1.0.0
plugins=com.betterclanbroadcasts.BetterClanBroadcastsPlugin
build=standard